layout_spectrum: 0.28960733652077986
typography_spectrum: 0.5218243635566628
color:
  saturation: 0.7808457406898869
  brandStrength: 0.07947223806818303
  lightness: 0.2438224160117973
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
  rhythmicContrast: 0.31818457895438046
content_rating:
  adult: false
github: true
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/f2fb5890-98c9-4842-9dae-a48732700876.jpg
  type: ''
author:
  name: Marleen Van Kelst
  email: info@anima.be
  url: marleenvankelst.be
name: YaniMa
navigation:
  - name: Wie is Marleen?
    id: 960411e4-fb0a-4153-8be3-fbc7df380022
    type: content
  - name: Massage
    id: cf8e711f-c970-4121-9790-dbb20d87a1c0
    type: content
  - name: Vind ons op Facebook
    url: 'https://www.facebook.com/YaniMa-320659001649650/'
    type: external
  - name: Beeldhouwen
    id: 276665c1-fd2b-4a35-86f1-f60da8a48179
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/3780e033-abe4-4d51-be73-6ce2a9689b86.jpg
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Marleen Van Kelst
content: []
description: 'Pralaya Yoga, Massage, Beeldhouwen'
purpose: []
